### ISSUE TITLE
Installation using a zip file

### ISSUE THREAD

**Issue by akallabeth** [stevesoltys/seedvault#89] opened 2020-06-16 09:51 UTC
Don´t know if that is possible, but could a `update-zip` be created for this and installed like `F-Droid privileged-extension` or similar on a rom?

**Comment by grote** [comment] 2020-06-16 12:21
Duplicate of #9 also related https://github.com/stevesoltys/seedvault/issues/20#issuecomment-517952961

That said, if signed with the platform key, it should be possible to do out-of-band update/installations. This is if I didn't forget any blocker there might be. However, these would need to come from the respective ROM, not Seedvault.

**Comment by akallabeth** [comment] 2020-06-17 10:40
@grote thanks for the clarification, assumed there might be some horrifyingly bad design choices on the android side in the way (security as in the nanny knows better, my way or the highway)
But that would mean with a custom rom and magisk, for example, it could be done to add another trusted signature for my personal stuff, or am I missing something?

**Comment by grote** [comment] 2020-07-09 12:12
> that would mean with a custom rom and magisk, for example, it could be done to add another trusted signature for my personal stuff, or am I missing something?

Don't know about Magisk, but a custom ROM could just sign an out-of band update zip with their key, so it could be flashed like the su-addon from LineageOS.

Also, I reopened #58 to investigate getting rid of the platform signing key requirement completely.

**Closed by grote** 2020-07-09 12:13 UTC
Labels: question
