### ISSUE TITLE
Reset recovery code

### ISSUE THREAD

**Issue by nickcalyx** [stevesoltys/seedvault#146] opened 2020-10-16 02:51 UTC
Step 1: initial use of Seedvault, get 12 words
Step 2: backup
Step 3: months later, want to restore from your backup, but you lost the 12 words
Step 4: want to create a new backup but you don't have the 12 words, there is no way to reset seedvault and get a new set of 12 words?
Step 5: forced to clear cache and app data in Settings/Apps & notifications in order to get a new set of 12 words

shouldn't there be a way to get a new encryption key in the UI?

**Comment by grote** [comment] 2020-10-16 11:44
@stevesoltys isn't this a duplicate of https://github.com/stevesoltys/seedvault/issues/62 ?

**Comment by stevesoltys** [comment] 2020-10-16 13:35
Looks like it, yeah. Thanks.

**Closed** 2020-10-16 13:35 UTC
Labels: duplicate, enhancement
