### ISSUE TITLE
Add 'Restore' menu option on new backup

### ISSUE THREAD

**Issue by r4v3r23** [stevesoltys/seedvault#88] opened 2020-06-16 08:40 UTC
add an option to restore previous backup on the inital 12 word seed screen when setting up on a fresh install/wipe

**Comment by grote** [comment] 2020-06-16 12:09
duplicate of #85 ?

**Comment by r4v3r23** [comment] 2020-06-16 12:11
yes, please add easy restore option

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Closed** 2020-06-16 12:12 UTC
Labels: duplicate
